### ISSUE TITLE
MindSet support?

### ISSUE THREAD

**Issue by konklone** [BarkleyUS/mindwave-python#1]
Hi - I just bought a MindSet with the intention of developing against it in Linux. I was under the (I now think mistaken) impression that the MindWave wouldn't allow capturing real-time raw data, but the MindSet would. Does this library support the MindSet as well? Should I just buy a MindWave instead?

**Comment by alanchrt** [comment]
I've actually never used the MindSet, so I'm not 100% sure. But, I did just dig through the "MindSet Communications Protocol" document, and it looks like it uses the same protocol as the MindWave. You might test it out. I'd be really curious to know if it works. Be sure to install the MindSet drivers from Neurosky first before using mindwave-python. You should end up with a /dev/whatever device when the driver is installed.

That said, MindWave and MindWave Mobile are newer, and they function really well with this library. I've used the MindWave on Linux for one project, and I haven't tested the MindWave Mobile on Linux (just Mac), but I don't foresee any problem using it as long as the Bluetooth pairs fine and sets up as a serial device.

My preference, having worked with both the MindWave ones is MindWave mobile, the Bluetooth one. The Bluetooth connection seems a lot more reliable than the usb RF adapter, and since the headsets automatically re-pair, you don't have to send the connect() and disconnect() signals from mindwave-python. They're just automatically connected when you create the Headset object.

I think the MindWave headsets are a bit cheaper (no headphones, mic, yadda yadda -- we never needed that stuff), so if you can still return the other one, I'd say MindWave Mobile is your best bet. Let me know what you end up doing!

**Comment by konklone** [comment]
OK, thanks! I'm actually going to hack on this tonight, at an event, and my goal is to get serial data flowing from the Mindset into Python, and to adapt this script if need be to handle it.

I think I'll probably end up getting the Mindwave Mobile, but in the meantime, I think the MindSet _should_ be usable...

I'll close this issue and re-open it with a pull request if I find any specific changes that need to be made.
