### ISSUE TITLE
?Device is busy

### ISSUE THREAD

**Issue by sleepytotoro** [BarkleyUS/mindwave-python#5]
Are there any problem with connecting two mindwave mobile at the same time via bluetooth?

It is giving me this error

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/serialposix.py", line 278, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
SerialException: could not open port /dev/tty.MindWaveMobile-DevA: [Errno 16] Resource busy: '/dev/tty.MindWaveMobile-DevA'

Is there any solution?

I appreciate your response.

**Comment by alanchrt** [comment]
There shouldn't be any issues, and I've done it successfully before.

Make sure you're using two different devices to open your connections and not the same one (`/dev/tty.MindWaveMobile-DevA`) twice. It probably would look something like this:

```
headset_A = mindwave.Headset('/dev/tty.MindWaveMobile-DevA', '625f')
headset_B = mindwave.Headset('/dev/tty.MindWaveMobile-DevB', '6227')
```

Check your /dev directory for the actual device names.

Let me know if that solves it. Also you may need to delete the bluetooth device and repair, or possibly restart your machine, because the error you're getting indicates the serial connection is still open, which can sometimes happen by a process not cleaning up properly.
